### ISSUE TITLE
Preview timeline

### ISSUE THREAD

**Issue by DanielLarsenNZ** [AzureCosmosDB/PriorityBasedExceution#2]
Hey @richagaur, 

Excited about this feature. We are using .NET SDK. Some questions:

1. Is there a non-preview SDK version yet or should we stay on 3.33.0-preview?
2. When will SDK come out of preview?
3. When will Cosmos feature come out of preview?
4. Is the Cosmos feature supported in production while in preview?

Thanks
-Daniel

**Comment by DanielLarsenNZ** [comment]
@richagaur any comments? 👆🏻

**Comment by richagaur** [comment]
Hi @DanielLarsenNZ 

Thanks for showing interest. Both the SDK and the feature will be out of preview next year.
However, we do support usage of this feature in production while in preview. 
I would recommend you test the feature in your dev/test environment and then begin usage in production.

Thanks!

**Comment by DanielLarsenNZ** [comment]
Great thanks @richagaur , does our subscription need to be activated for this? I filled out a form a few weeks ago.

**Comment by richagaur** [comment]
We have enabled the feature on your shared subscription and account.
